### ISSUE TITLE
レスポンスステータスのみを返すAPIのステータスが異なっていてもfailしない

### ISSUE THREAD

**Issue by k-minemoto** [recruit-tech/agreed-core#60]
```:javascript
// agreed.js
module.exports = [
{
  request: {
    path: '/api/sample/:id',
    method: 'PUT',
    body: [
      {value:'test'}
    ],
    values: {
      id: 1,
    },
  },
  response: {
    status: 204,
  },
}]
```
クライアントテストの実行
```:bash
$ agreed-client --host localhost --port 8080 --path ./agreed.js
```

この時、実際のサーバーステータスが200で戻ってきても、テスト結果がOKとなります。

https://github.com/recruit-tech/agreed-client/blob/master/lib/reporter.js#L15
を見る限りではdiffかschemaErrorsのどちらかにデータがあるとfailするようになってますが、この時のresultの中身は
```:javascript
{ body: '', diff: {}, status: [ 204, 200 ] }
```
となっており、failと判定されません（※isEmpty(result)は、diffが存在するので常にfalseです）。
よって詰め込む側がdiffに入れるかreporter側がstatusの有無を見るかになりますが、単純にclientのcheckResponseの処理でdiffに入れ損ねているように見えます。

**Comment by yosuke-furukawa** [comment]
solved.
